version: '3.9'

services:
  # MongoDB Container
  mongodb:
    container_name: accord_mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongodb:/data/db

  # Node Container
  node:
    container_name: accord_node_container
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/Accord
    environment:
      - PORT=${PORT}
      - MONGODB_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - JWT_SECRET = ${JWT_SECRET}
      - JWT_EXPIRES_IN = ${JWT_EXPIRES_IN}
      - CLOUD_NAME = ${CLOUD_NAME}
      - API_KEY = ${API_KEY}
      - API_SECRET = ${API_SECRET}
      - CLOUDINARY_URL = ${CLOUDINARY_URL}
    depends_on:
      - mongodb

volumes:
  mongodb: {}
